-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-06-25 16:03:17 EDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE education (
    education_id INTEGER NOT NULL,
    university   VARCHAR2(255),
    major        VARCHAR2(255),
    gpa          FLOAT,
    coursework   VARCHAR2(1000),
    location     VARCHAR2(255),
    user_id      INTEGER NOT NULL
);

ALTER TABLE education ADD CONSTRAINT education_pk PRIMARY KEY ( education_id );

CREATE TABLE project (
    project_id  INTEGER NOT NULL,
    title       VARCHAR2(255),
    description VARCHAR2(255),
    user_id     INTEGER NOT NULL
);

ALTER TABLE project ADD CONSTRAINT project_pk PRIMARY KEY ( project_id );

CREATE TABLE user_data (
    user_id    INTEGER NOT NULL,
    first_name VARCHAR2(255),
    last_name  VARCHAR2(255),
    phone      NUMBER,
    email      VARCHAR2(255),
    location   VARCHAR2(255),
    languages  VARCHAR2(255)
);

ALTER TABLE user_data ADD CONSTRAINT user_data_pk PRIMARY KEY ( user_id );

CREATE TABLE work_experience (
    work_experience_id INTEGER NOT NULL,
    title              VARCHAR2(255),
    company            VARCHAR2(255),
    description        VARCHAR2(1000),
    start_date         DATE,
    end_date           DATE,
    user_id            INTEGER NOT NULL
);

ALTER TABLE work_experience ADD CONSTRAINT work_experience_pk PRIMARY KEY ( work_experience_id );

ALTER TABLE education
    ADD CONSTRAINT education_user_data_fk FOREIGN KEY ( user_id )
        REFERENCES user_data ( user_id );

ALTER TABLE project
    ADD CONSTRAINT project_user_data_fk FOREIGN KEY ( user_id )
        REFERENCES user_data ( user_id );

ALTER TABLE work_experience
    ADD CONSTRAINT work_experience_user_data_fk FOREIGN KEY ( user_id )
        REFERENCES user_data ( user_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             0
-- ALTER TABLE                              7
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
